### ISSUE TITLE
"lb-service" docker build issue

### ISSUE THREAD

**Issue by youwalther65** [aws-ia/terraform-aws-ecs-blueprints#77]
## Description

Running "lb-service" example after successfully deploying "core-infra" I run into docker build issue

If your request is for a new feature, please use the `Feature request` template.

- [x ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 
$ cat .terraform/modules/modules.json | jq
{
  "Modules": [
    {
      "Key": "codepipeline_ci_cd",
      "Source": "../../modules/codepipeline",
      "Dir": "../../modules/codepipeline"
    },
    {
      "Key": "codepipeline_s3_bucket",
      "Source": "registry.terraform.io/terraform-aws-modules/s3-bucket/aws",
      "Version": "3.4.0",
      "Dir": ".terraform/modules/codepipeline_s3_bucket"
    },
    {
      "Key": "container_image_ecr",
      "Source": "registry.terraform.io/terraform-aws-modules/ecr/aws",
      "Version": "1.4.0",
      "Dir": ".terraform/modules/container_image_ecr"
    },
    {
      "Key": "ecs_service_definition",
      "Source": "../../modules/ecs-service",
      "Dir": "../../modules/ecs-service"
    },
    {
      "Key": "ecs_service_definition.task_main_app_container",
      "Source": "../ecs-container-definition",
      "Dir": "../../modules/ecs-container-definition"
    },
    {
      "Key": "service_alb",
      "Source": "registry.terraform.io/terraform-aws-modules/alb/aws",
      "Version": "7.0.0",
      "Dir": ".terraform/modules/service_alb"
    },
    {
      "Key": "service_alb_security_group",
      "Source": "registry.terraform.io/terraform-aws-modules/security-group/aws",
      "Version": "4.13.1",
      "Dir": ".terraform/modules/service_alb_security_group"
    },
    {
      "Key": "codebuild_ci",
      "Source": "../../modules/codebuild",
      "Dir": "../../modules/codebuild"
    },
    {
      "Key": "ecs_service_definition.task_sidecar_containers",
      "Source": "../ecs-container-definition",
      "Dir": "../../modules/ecs-container-definition"
    },
    {
      "Key": "service_task_security_group",
      "Source": "registry.terraform.io/terraform-aws-modules/security-group/aws",
      "Version": "4.13.1",
      "Dir": ".terraform/modules/service_task_security_group"
    },
    {
      "Key": "",
      "Source": "",
      "Dir": "."
    }
  ]
}

- Terraform version: 1.2.4

- Provider version(s):

Terraform v1.2.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.36.1
+ provider registry.terraform.io/hashicorp/random v3.4.3

## Reproduction Code [Required]

terraform init
teraform plan
terraform apply -auto-aprove

local "docker build ." in directory "terraform-aws-ecs-blueprints/application-code/ecsdemo-frontend" gave same docker build error
## Expected behavior

Successful docker build, docker push and container image in ECR registry, which can be used for ECS service

### Terminal Output Screenshot(s)
CodeBuild -> Build Logs
...
nokogiri-1.13.9-x86_64-linux requires ruby version < 3.2.dev, >= 2.6, which is
incompatible with the current version, ruby 2.5.9p229

The command '/bin/sh -c apt-get update && apt-get -y install iproute2 curl jq libgmp3-dev ruby-dev build-essential sqlite libsqlite3-dev python3 python3-pip &&     gem install bundler:1.17.3 &&     bundle install &&     pip3 install awscli netaddr &&     apt-get autoremove -y --purge &&     apt-get remove -y --auto-remove --purge ruby-dev libgmp3-dev build-essential libsqlite3-dev &&     apt-get clean &&     rm -rvf /root/* /root/.gem* /var/cache/*' returned a non-zero code: 5

[Container] 2022/10/24 13:19:52 Command did not exit successfully docker build -t $REPO_URL $FOLDER_PATH exit status 5

**Comment by arvindsoni80** [comment]
Checking
